services:
  postgres:
    image: postgres:16
    container_name: aura_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: retinal_system
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - aura_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d retinal_system"]
      interval: 10s
      timeout: 5s
      retries: 10

  pgadmin:
    image: dpage/pgadmin4
    container_name: aura_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - aura_network

  minio:
    image: minio/minio:latest
    container_name: aura_minio
    command: server /data --console-address ":9001"
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    networks:
      - aura_network

  minio-init:
    image: minio/mc:latest
    container_name: aura_minio_init
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until mc alias set local http://minio:9000 minioadmin minioadmin123 2>/dev/null; do
        echo 'waiting minio...'; sleep 2;
      done;
      mc mb -p local/aura || true;
      mc anonymous set download local/aura || true;
      exit 0;
      "
    networks:
      - aura_network
    restart: "no"

  ai-core:
    build:
      context: ./ai-core
      dockerfile: Dockerfile
    container_name: aura_ai_core
    restart: always
    ports:
      - "8000:8000"
    networks:
      - aura_network
    # volumes:
    #   - ./ai-core/artifacts:/app/artifacts

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: aura_backend
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      minio-init:
        condition: service_completed_successfully
      ai-core:
        condition: service_started
      minio:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/retinal_system
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456

      AI_BASE_URL: http://ai-core:8000

      # internal (container->container)
      MINIO_ENDPOINT: http://minio:9000

      # public (browser sẽ gọi URL này)
      MINIO_PUBLIC_ENDPOINT: http://localhost:9000

      # important: presign offline (avoid auto region/location lookup)
      MINIO_REGION: us-east-1

      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_BUCKET: aura
      MINIO_PRESIGN_EXPIRY_SECONDS: 600
    networks:
      - aura_network

  frontend:
    build:
      context: ./frontend
    container_name: aura_frontend
    restart: always
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:8080
    networks:
      - aura_network

volumes:
  pgdata:
    name: aura_pgdata
  pgadmin-data:
    name: aura_pgadmin_data
  minio-data:
    name: aura_minio_data

networks:
  aura_network:
    driver: bridge
